### ISSUE TITLE
Respawn Player

### ISSUE THREAD

**Issue by asantacoloma** [ufosc/marston-vs-west#2]
Devise a way to check if player has gone off screen and respawn them back on stage.

**Comment by BenjaminECohen** [comment]
Idea for Respawn Animation: Giant book that drops down that the player pops out of. (Would need to add book sprites to character sheets). Need immunity frames for X amount of time. Possible sprite opacity change/mod till the immunity frames are over.

**Comment by asantacoloma** [comment]
Re-spawn and KO functions now exist in game, players can currently jump off screen and get re-spawned at start point. Further updates to this issue would be to include temporary immunity for newly re-spawned players.

**Comment by BenjaminECohen** [comment]
Working on respawning animation with the book crashing down. Player control has been taken away during the event and the alpha for the character has been halved denoting invulnerability. Player invulnerability not added yet.

**Comment by BenjaminECohen** [comment]
Added character alpha "blinking" and decreased total invincibility time.
