### ISSUE TITLE
Hitboxes

### ISSUE THREAD

**Issue by asantacoloma** [ufosc/marston-vs-west#4]
Currently player attacks are purely animation and do not affect other players. We need to develop a way to register when a player's attack actually is in contact with another player.

**Comment by GregFussell** [comment]
got this

**Comment by BenjaminECohen** [comment]
Just to leave a comment on what I currently have been doing for the Hitboxes and some optimization changes:

updateInput function changes: Restructured the updateInput function’s if-else statements, so blocking is overridden by attacks and movement is overridden by blocking and attacks. Added statements at the beginning and in the “left” and “right” if-else statements to update the hitVelocity variable to combat knockback and decrease (or increase) it faster. Slowed down the x velocity of a Fighter while in the air (250 -> 200). Jumping overrides left and right movement, allowing for jumping while moving left or right.

Added a shielding variable to the Fighter class to allow hits to not deal damage while shield is up

Edited the hit Function into two separate hit functions individually made for each fighter and disabled damage when the character is in the invicible state after respawn and/or when the fighter is blocking.

Added hitVelocity variable to Fighter class that determines the knockback velocity of the character when they are struck at a certain damage amount.
