### ISSUE TITLE
Unintentional Collision Dodging

### ISSUE THREAD

**Issue by swiftlee** [ufosc/marston-vs-west#41]
It seems that when two players fall inside a certain range of each other they are invincible to attacks. I guess the question is what do we want to occur on an event such as this?

Here is an example:

https://gyazo.com/fdeba550577373dd91aec92d9fe2e508

**Comment by asantacoloma** [comment]
Great find, thanks for having a clear example of what issue you are referring to, it may be interesting to have as a mechanic that if you are hugging the opponent they cannot hit you (similar to grabbing in boxing), on the other hand we can fix this bug quite easily by adjusting the location and size of the hit and hurt boxes of fighters and their respective attacks.
